version: '3.8'

services:
  wiremock:
    image: wiremock/wiremock:latest
    container_name: wiremock-monitoreo
    ports:
      - "8080:8080"
    volumes:
      - ./frontend/wiremock/mappings:/home/wiremock/mappings
      - ./frontend/wiremock/__files:/home/wiremock/__files
    command: ["--global-response-templating", "--disable-gzip", "--verbose"]
