services:
  db-init:
    image: mcr.microsoft.com/mssql/server:2022-latest
    entrypoint: ["/bin/bash", "-c"]
    command: /docker-entrypoint-initdb.d/init-db.sh
    environment:
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD:-desa123$}
      SQLSERVER_HOST: db
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - climate-risk-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      db-init:
        condition: service_completed_successfully
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Development}
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=${DB_NAME:-ClimateRiskDb};User Id=sa;Password=${MSSQL_SA_PASSWORD:-desa123$};TrustServerCertificate=True;Encrypt=False"
    ports:
      - "${BACKEND_API_PORT:-5001}:8080"
    networks:
      - climate-risk-network

networks:
  climate-risk-network:
    external: true
    name: climate-risk-network
